Emscriame: Build with Emscripten

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Emscripten
      run: |
        # Install emsdk (Emscripten SDK)
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest
        source ./emsdk_env.sh  # This sets up the environment variables for emcc to work
        cd ..

    - name: Create Output Directory
      run: mkdir output

    - name: Build with Emscripten
      run: |
        emcc source.cpp -o output/output.js
