name: Build with Emscripten

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Emscripten toolchain
      - name: Setup Emscripten toolchain
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest  # Emscripten version to install (optional)
          no-install: false  # Don't skip installation
          no-cache: false  # Cache is not being used
          update: true
          update-tags: false

      # Step 3: Find and source emsdk_env.sh
      - name: Set up Emscripten environment
        run: |
          # Locate the emsdk_env.sh script and source it
          source $(find $HOME -type f -name emsdk_env.sh | head -n 1)

      # Step 4: Install build dependencies (if needed)
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      # Step 5: Build project with Emscripten
      - name: Build project with Emscripten
        run: |
          emcc src/main.cpp -o build/main.js  # Run Emscripten build

      # Step 6: Upload build artifacts (optional)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: build/
