name: Build with Emscripten

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Emscripten toolchain
      - name: Setup Emscripten toolchain
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest  # Emscripten version to install (optional)
          no-install: false  # Don't skip installation
          no-cache: false  # Cache is not being used
          update: true
          update-tags: false

      # Step 3: Set up Emscripten environment (source emsdk_env.sh)
      - name: Set up Emscripten environment
        run: |
          # Locate the emsdk_env.sh script and source it
          source $(find $HOME -type f -name emsdk_env.sh | head -n 1)

      # Step 4: (Optional) Install build dependencies (if needed)
      # This is an optional step and can be skipped if you don't need additional dependencies
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      # Step 5: List files in the repository for debugging (to verify the file path)
      - name: List files in repository
        run: |
          ls -R

      # Step 6: Compile with Emscripten and generate .js.metadata files
      - name: Build project with Emscripten and generate .js.metadata files
        run: |
          emcc ./src/main.cpp -o build/main.js --js-meta=build/main.js.metadata  # Adjust the path based on actual location of main.cpp

      # Step 7: Upload build artifacts (optional)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: build/
