name: Generate Emscripten Filesystem

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-filesystem:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Emscripten
      run: |
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest
        source ./emsdk_env.sh

    - name: Generate Emscripten Filesystem
      run: |
        mkdir output
        emcc --preload-file data -o output/filesystem.js

    - name: Upload Filesystem Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: emscripten-filesystem
        path: output/
