name: Build with Emscripten

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Emscripten manually (fallback if setup action doesn't work)
      - name: Install Emscripten manually
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh

      # Step 3: Install build dependencies
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      # Step 4: Verify emcc is available
      - name: Verify Emscripten installation
        run: |
          emcc --version

      # Step 5: Build your project
      - name: Build project with Emscripten
        run: |
          # Example: Run Emscripten's emcc to compile your project
          emcc src/main.cpp -o build/main.js

      # Optional: Step 6 - Upload build artifacts (if you want to store the output)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: build/
